### ISSUE TITLE
Deprecate shared-lib

### ISSUE THREAD

**Issue by davidlatwe** [davidlatwe/rezup#62]
Shared-lib shares Python packages across revisions, one could define it in recipe as follow :

```toml
# rezup.toml
[shared]
name = "production"
requires = [
    "pyside2",
    "Qt5.py",
]
```

 It's meant for faster deployment but in reality it doesn't help much since we rarely do much change for one container in a short period. And the problems come with this design could be bigger than that small speed boost.

E.g., changing shared lib for new revision that potentially could breaks the old ones. (those old revisions may still be needed if new one fails to work). Also, for package like `PySide2` that contains `.dll` will refuse to be removed when updating and cause error.
